server:
  port: 8001
  ssl:
    key-store: classpath:ssl/keystore.jks
    key-store-type: JKS
    key-store-password: "${KEYSTORE_PASSWORD}"

spring:
  mvc:
    view:
      prefix: WEB-INF/views/
      suffix: .jsp

searchApi:
  host: http://sch.phakr.com:8002/api/search

logging:
  file:
    path: /svc/search_web/logs
    name: search_web
    level: DEBUG

webclient:
  connection-timeout: 5000
  max-connections: 100
  max-idle-time: 60
  max-life-time: 60
  pending-acquire-timeout: 5000
  pending-acquire-maxCount: -1
  evict-in-background: 30
  metrics: false
  response-timeout: 3000
  read-timeout: 10000
  write-timeout: 3000
  max-in-memory-size: 100


search:
  client-auth: N

# jsp config
javascript:
  company-name: PHA
  menu:
    99999:
      orderBy: 1
      name: 통합검색
      icon: icon01
      detail: Y
    20000:
      orderBy: 2
      name: 전자결재
      icon: icon02
      detail: Y
    40000:
      orderBy: 3
      name: 표준관리
      icon: icon03
      detail: Y
    50000:
      orderBy: 4
      name: 임직원
      icon: icon04
      detail: N

  pagination:
    defaultPageSize: 10
    pageBlockSize: 10
    moreViewSize: 10


