server:
  port: 8001

spring:
  mvc:
    view:
      prefix: WEB-INF/views/
      suffix: .jsp

searchApi:
  host: http://sch.phakr.com:8002/api/search


# jsp config
javascript:
  menuId:
    idx_02_eapproval:
      sectionCode: 20000
      sectionName: 전자결재
      sectionIcon: icon01
    idx_02_regulation:
      sectionCode: 40000
      sectionName: 규정관리
      sectionIcon: icon01
    idx_03_people:
      sectionCode: 50000
      sectionName: 임직원
      sectionIcon: icon01
    ALL:
      sectionCode: 99999
      sectionName: 통합검색
      sectionIcon: icon01

  attach_ext:
    [doc, docx, ppt, pptx, xls, xlsx, pdf, txt, psd]

  pagination:
    defaultPageSize: 10
    pageBlockSize: 10
    moreViewSize: 10

